version: 0.2
phases:
  pre_build:
    commands:
     - BUILD_VERSION="${CODEBUILD_RESOLVED_SOURCE_VERSION:="XXXXXX"}"
  build:
    commands:
      - echo building here
      - zip -ur dist.zip README.md
  post_build:
    commands:
      - aws s3 cp --no-progress dist.zip s3://${S3_BUILD_BUCKET}/builds/releasable-target/objects/${BUILD_VERSION}/dist.zip
      - aws s3 cp --no-progress dist.zip s3://${S3_BUILD_BUCKET}/builds/releasable-target/refs/${CODEBUILD_WEBHOOK_TRIGGER}/dist.zip

