version: 0.2
phases:
  pre_build:
    commands:
     - BUILD_VERSION="${CODEBUILD_RESOLVED_SOURCE_VERSION:="XXXXXX"}"
     - export SHA1_START=`echo ${BUILD_VERSION} | cut -c -2`
     - export SHA1_END=`echo ${BUILD_VERSION} | cut -c 3-`

  build:
    commands:
      - bin/create_build_file
      - echo building here
      - rm -rf target
      - mkdir target
      - # lambda component
      - mkdir target/lambda
      - cp src/main/bash/* target/lambda
      - cd target/lambda
      - zip -ur ../dist.zip *
      - cd ../..
      - # web component
      - mkdir target/web
      - rsync --exclude='config.js' src/main/web/* target/web
      - cd target/web
      - zip -ur ../cloudfront.zip *
      - cd ../..
  post_build:
    commands:
      - aws s3 cp --no-progress target/dist.zip s3://${S3_BUILD_BUCKET}/builds/releasable-target/objects/${SHA1_START}/${SHA1_END}/dist.zip
      - aws s3 cp --no-progress target/cloudfront.zip s3://${S3_BUILD_BUCKET}/builds/releasable-target/objects/${SHA1_START}/${SHA1_END}/cloudfront.zip
      - aws s3 cp --no-progress target/dist.zip s3://${S3_BUILD_BUCKET}/builds/releasable-target/refs/${CODEBUILD_WEBHOOK_TRIGGER}/dist.zip
      - aws s3 cp --no-progress target/cloudfront.zip s3://${S3_BUILD_BUCKET}/builds/releasable-target/refs/${CODEBUILD_WEBHOOK_TRIGGER}/cloudfront.zip

