version: 0.2
phases:
  pre_build:
    commands:
     - BUILD_VERSION="${CODEBUILD_RESOLVED_SOURCE_VERSION:="XXXXXX"}"
     - export SHA1_START=`echo ${BUILD_VERSION} | cut -c -2`
     - export SHA1_END=`echo ${BUILD_VERSION} | cut -c 3-`
  build:
    commands:
     - make clean install
